schedules:
  - cron: "0 4 * * *"
    displayName: "Daily at 4 AM"
    always: true
    branches:
      include:
        - main

variables:
  - group: Vars

jobs:
  - job: sync
    displayName: Sync Letterboxd to Radarr
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.x"
        displayName: "Install Node.js"

      - script: npm install
        displayName: "Install dependencies"

      - script: node run.js
        displayName: "Run letterboxd-to-radarr sync"
