schedules:
  - cron: "0 4 * * *"
    displayName: "Every day at 4 AM"
    always: true
    branches:
      include:
        - main

variables:
  - group: ApiKeys

jobs:
  - job: sync_to_radarr
    displayName: Sync Letterboxd to Radarr
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.x"
        displayName: "Install Node.js"

      - script: |
          npm install
        displayName: "Install Dependencies"

      - script: |
          node run.js
        displayName: "Run Sync Script"
